config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/index'
  resources :users do
    resources :tasks
  end


  post 'users/login_user', :to => 'users#login_user', as: 'login_user'
  
  root 'users#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :task, dependent: :destroy
    # validates :user, presence: true,
    #                   length: { minimum: 5 }
    def self.authenticate(email, login_password)
        user = User.find_by email: email
        return user
    end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @task = @user.task.create(task_params)
        redirect_to user_path(@user)
    end
    
    def edit
      @task = Task.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
     #@task = @user.task.update(task_params)
      if @user.task.update(task_params)
        redirect_to @task
      else
        render 'edit'
      end
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
   
        redirect_to task_path
    end

     
      private
        def task_params
          params.require(:task).permit(:title, :description, :start, :end )
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.all
    end

    def show
        @user = User.find(params[:id])
    end  

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def login_user
    
        @x = user_params[:email]
        @y = user_params[:password]
        print @x

        @user = User.authenticate(@x, @y)
        
        
        #@user = User.where("email = ?", params[:email]).select( "name, email, password")
        
        if User.exists?( email: @x ) && User.exists?( password: @y )
            redirect_to @user     
        else
            render 'login'
        end 

    end    

    def create
        @user = User.new(user_params)
    
        if User.exists?( email: @user.email )
            render 'new'
        else
            @user.save    
            redirect_to @user
        end    
    end

    def update
        @user = User.find(params[:id])
       
        if @user.update(user_params)
          redirect_to @user
        else
          render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
     
        redirect_to users_path
    end
       
      private
        def user_params
          params.require(:user).permit(:name, :email, :password)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserTasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with(model: @task, local: true) do |form| %>

<% if @task.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@tasks.errors.count, "error") %> Edit Successfull
  </h2>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.email_field :email %>
</p>

<p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing tasks</h1>

<table>
 <tr>
   <th>Title</th>
   <th>Description</th>
   <th>Start</th>
   <th>End</th>
 </tr>

 <% @task.each do |task| %>
   <tr>
     <td><%= task.title%></td>
     <td><%= task.description %></td>
     <td><%= task.start%></td>
     <td><%= task.end %></td>
     <td><%= link_to 'Show', task_path(task) %></td>
     <td><%= link_to 'Edit', edit_task_path(task) %></td>
     <td><%= link_to 'Destroy', task_path(task),
        method: :delete,
        data: { confirm: 'Delete Task?' } %></td>
   </tr>
 <% end %>
</table>

app/views/tasks/show.html.erb
      <p>
        <strong>Title:</strong>
        <%= @user.Name %>
      </p>
       
       
      <h2>Add a Task:</h2>
      <%= form_with(model: [ @user, @user.tasks.build ], local: true) do |form| %>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </p>
        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description %>
        </p>
        <p>
        <%= form.label :start %><br>
        <%= form.text_field :start %>
        </p>
        <p>
        <%= form.label :end %><br>
        <%= form.text_field :end %>
        </p>
        <p>
          <%= form.submit  %>
        </p>
      <% end %>
       
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_with(model: @user, local: true) do |form| %>

<% if @user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@users.errors.count, "error") %> Edit Successfull
  </h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.email_field :email %>
</p>

<p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <%= link_to 'Logout', root_path, :class => 'btn btn-default'%>  
<table class="table table-striped" >
 <tr>
   <th>Name</th>
   <th>Email</th>
   <th></th>
   <th>Action</th>
   <th></th>
 </tr>

 <% @user.each do |user| %>
   <tr>
     <td><%= user.name%></td>
     <td><%= user.email %></td>
     <td><%= link_to 'Show', user_path(user) %></td>
     <td><%= link_to 'Edit', edit_user_path(user) %></td>
     <td><%= link_to 'Destroy', user_path(user),
        method: :delete,
        data: { confirm: 'Delete User?' } %></td>
   </tr>
 <% end %>
</table>

app/views/users/login.html.erb
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
<%= form_with scope: :user,url: login_user_path , local: true do |form| %>
<div class="container form-group">
<p>
  
  <%= form.label :email%><br>
  <%= form.email_field :email, :class => 'form-control' %>
</p>

<p>
    <%= form.label :password%><br>
    <%= form.password_field :password ,:class => 'form-control'%>
</p>

<p>
  
  <%= form.submit 'Login' , :class => 'btn btn-default' %>

</p>
<%= link_to 'New User', new_user_path, :class => 'btn btn-default'%>
</div>
<% end %>

app/views/users/new.html.erb
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
<%= form_with scope: :user, url: users_path, local: true do |form| %>

<% if @user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@user.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container form-group">
<p>
  <%= form.label :name %><br>
  <%= form.text_field :name ,:class => 'form-control'%>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.email_field :email ,:class => 'form-control'%>
</p>

<p>
    <%= form.label :password %><br>
    <%= form.password_field :password ,:class => 'form-control'%>
</p>

<p>
  <%= form.submit 'Submit', :class => 'btn btn-default'  %>
</p>
<% end %>

<%= link_to 'Back', root_path, :class => 'btn btn-default' %>
</div>

app/views/users/show.html.erb
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
<p id="notice"><%= notice %></p>
<%= link_to 'Logout', root_path, :class => 'btn btn-default'%>  
<div class="container">
    <div class="jumbotron">    
<p>
        <strong>Username:</strong>
        <%= @user.name %>
      </p>
       
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p> 
      
     
      <% if @user.name == "admin" %>
          <%= link_to 'List Users and tasks', controller: 'users' %>
      <% end %>
    </div>
    </div>
    <div class="container">
        <div class="jumbotron">  
      <h2>Tasks</h2>
      <% @user.task.each do |task| %>
      <div class="container">
          <div class="jumbotron">  
        <p>
          <strong>Title:</strong>
          <%= task.title %>
        </p>
       
        <p>
          <strong>Description:</strong>
          <%= task.description %>
        </p>
        <p>
            <strong>Start:</strong>
            <%= task.start %>
        </p>
        <p>
            <strong>End:</strong>
            <%= task.end %>
        </p>
          </div>
          </div>
      <% end %>
        </div>
        </div>
      

      <%= form_with(model: [ @user, @user.task.build ], local: true) do |form| %>
      <div class="container form-group"> 
          <h2>Add a task:</h2>
      <p>
          <%= form.label :title %><br>
          <%= form.text_field :title ,:class => 'form-control'%>
        </p>
        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description, :class => 'form-control' %>
        </p>
        <p>
            <%= form.label :start %><br>
            <%= form.text_field :start, :class => 'form-control' %>
          </p>
          <p>
            <%= form.label :end %><br>
            <%= form.text_field :end , :class => 'form-control'%>
          </p>
        <p>
          <%= form.submit 'Submit' , :class => 'btn btn-default'%>
        </p>
        <%= link_to 'Edit', edit_user_path(@user) %> |
        <%= link_to 'Back', users_path %>
      </div>  
      <% end %>
       
      
      

app/views/welcome/index.html.erb
<h1>Signup or Login User</h1>
<%= link_to 'Login', login_user %>
<%= link_to 'Signup', controller: 'tasks' %>